In [1]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [2]:
np.array(["vbhvh", 2, 3])

array(['vbhvh', '2', '3'], dtype='<U5')

In [3]:
np.array([4, 2, 3])

array([4, 2, 3])

In [4]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [6]:
x = np.array([[1, 2], [3, 4]])
x.shape

(2, 2)

In [8]:
x

array([[1, 2],
       [3, 4]])

In [7]:
x.reshape(1,2,2)

array([[[1, 2],
        [3, 4]]])

In [15]:
np.ones((1,2,5,3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [16]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [17]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [18]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [20]:
x[1][0]

3

In [21]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [22]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [23]:
a = [1, 2]
type(a)

list

In [ ]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

In [24]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [ ]:
def func1(i,j,k):
    return i == j

In [32]:
np.fromfunction(lambda i, j, k: i == j, (3,5,3), dtype=int)

array([[[ True,  True,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [ True,  True,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [ True,  True,  True],
        [False, False, False],
        [False, False, False]]])

In [35]:
a = np.fromstring('234,234,255,1,0',sep=',')
a

array([234., 234., 255.,   1.,   0.])

In [38]:
np.zeros((5,5,))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
np.arange(3)

array([0, 1, 2])

In [41]:
np.arange(3.0)

array([0., 1., 2.])

In [42]:
np.arange(3,7)

array([3, 4, 5, 6])

In [43]:
np.arange(3,7,2)

array([3, 5])

In [44]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [45]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [49]:
np.arange(20).reshape((1,4,-1))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [53]:
np.arange(20).reshape((-1,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [55]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [54]:
np.diag(x)

array([[(1, 2), (0, 0)],
       [(0, 0), (3, 4)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [56]:
np.random.rand(2,3)

array([[0.04480959, 0.09828221, 0.75149076],
       [0.5396646 , 0.42228753, 0.46980026]])

In [57]:
np.random.randn(4,3)

array([[ 1.00403047,  1.57250422,  1.56595696],
       [ 1.54748989,  0.41442617,  1.48154644],
       [-0.52331513, -0.01312725,  0.72861426],
       [-1.18475656,  0.53049204,  0.25572311]])

In [58]:
np.random.randint(1,10)

3

In [60]:
x = np.random.randint(1,100,(4,4))

In [62]:
x

array([[73, 93, 49, 36],
       [20, 45, 99, 36],
       [47, 44, 83, 88],
       [ 4, 38, 22, 90]])

In [61]:
x[x>50]

array([73, 93, 99, 83, 88, 90])

In [63]:
np.sqrt(x)

array([[8.54400375, 9.64365076, 7.        , 6.        ],
       [4.47213595, 6.70820393, 9.94987437, 6.        ],
       [6.8556546 , 6.63324958, 9.11043358, 9.38083152],
       [2.        , 6.164414  , 4.69041576, 9.48683298]])

In [64]:
np.exp(x)

array([[5.05239363e+31, 2.45124554e+40, 1.90734657e+21, 4.31123155e+15],
       [4.85165195e+08, 3.49342711e+19, 9.88903032e+42, 4.31123155e+15],
       [2.58131289e+20, 1.28516001e+19, 1.11286375e+36, 1.65163625e+38],
       [5.45981500e+01, 3.18559318e+16, 3.58491285e+09, 1.22040329e+39]])