In [1]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [2]:
n2=np.array([[10,20,30,40],[20,30,40,50]])
n2

array([[10, 20, 30, 40],
       [20, 30, 40, 50]])

In [5]:
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [6]:
n1=np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
n1=np.arange(10,50,2)
n1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [5]:
n1=np.random.randint(1,100,12)
n1

array([67, 32, 84, 78, 67,  5, 45, 17,  7, 76, 20, 47])

In [6]:
n1>50

array([ True, False,  True,  True,  True, False, False, False, False,
        True, False, False])

In [9]:
n1[n1>50]

array([67, 84, 78, 67, 76])

In [10]:
n1=np.array([[1,2,3],[2,3,4]])
n1.shape

(2, 3)

In [11]:
n1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
n1.shape=(3,2)
n1.shape

(3, 2)

In [13]:
n1

array([[1, 2],
       [3, 2],
       [3, 4]])

In [14]:
n2=np.array([[6,7,8],[5,6,7]])
n2.shape

(2, 3)

In [15]:
n2

array([[6, 7, 8],
       [5, 6, 7]])

In [16]:
n2.shape=(3,2)
n2.shape

(3, 2)

In [17]:
n2

array([[6, 7],
       [8, 5],
       [6, 7]])

In [18]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [19]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [20]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [21]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([40,50,60,70,80,90])
np.intersect1d(n1,n2)

array([40, 50, 60])

In [22]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [23]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [24]:
np.sum([n1,n2])

600

In [25]:
np.sum([n1,n2],axis=0)

array([ 50,  70,  90, 110, 130, 150])

In [26]:
np.sum([n1,n2],axis=1)

array([210, 390])

In [27]:
n1=n1+1
n1

array([11, 21, 31, 41, 51, 61])

In [43]:
np.mean(n1)

36.0

In [44]:
np.median(n1)

36.0

In [28]:
np.std(n1)

17.07825127659933

In [29]:
n1.mean()

36.0

In [33]:
a=np.array(['nlnskr',23,36])
a

array(['nlnskr', '23', '36'], dtype='<U11')

In [34]:
type(a)

numpy.ndarray

In [39]:
x=np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13,]])
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [40]:
x.shape

(4, 3)

In [42]:
x.reshape(3,4)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [43]:
x.reshape(6,2)

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [44]:
x.reshape(2,6)

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [55]:
x.reshape(1,2,6)

array([[[ 2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13]]])

In [51]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
np.zeros([3,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [59]:
np.zeros([1,2,3,4]) #here 2=metrix,3=rows,4=coloumn

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [60]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [50]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [51]:
len(x)

2

In [52]:
x[0]

(1, 2)

In [53]:
x[1]

(3, 4)

In [54]:
x[0][1]

2

In [55]:
z=np.mat(np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13,]]))
z

matrix([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]])

In [64]:
np.mat('1 2;3 4')

matrix([[1, 2],
        [3, 4]])

In [74]:
a=np.array([1,2],dtype=np.float)
a

<ipython-input-74-3a374ff7fbc5>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([1,2],dtype=np.float)


array([1., 2.])

In [1]:
import numpy as np

In [2]:
a=[1,2]
type(a)

list

In [3]:
a=(1,2,'nln')
type(a)

tuple

In [4]:
def fun1(i,j,k):
    return i==j
np.fromfunction(lambda i,j,k:i==j,(3,5,3),dtype=int)

array([[[ True,  True,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [ True,  True,  True],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [ True,  True,  True],
        [False, False, False],
        [False, False, False]]])

In [6]:
l1=(87,56,90,34,2,5,17,98)
fin_list=list(filter(lambda x:(x%2==0),l1))

In [7]:
fin_list

[56, 90, 34, 2, 98]

In [8]:
x=np.fromstring('1,2,3,4,5,6,7,8,9',sep=',')
x

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
np.logspace(2,3,num=4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [23]:
np.arange(20).reshape(4,5,-1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [24]:
np.arange(20).reshape(-1,4,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [25]:
x

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
np.diag(x)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [27]:
np.random.rand(2,3)

array([[0.82471483, 0.78063548, 0.75798314],
       [0.97195786, 0.20515465, 0.3250399 ]])

In [28]:
np.random.randn(2,3)

array([[-0.07387985, -1.23015207,  1.17344917],
       [-0.85750911, -0.31180691,  1.36412685]])

In [41]:
y=np.random.randint(1,100,12)
y

array([62, 64, 52, 13, 16,  3, 43, 63, 86, 62, 62, 13])

In [42]:
y[y>50]

array([62, 64, 52, 63, 86, 62, 62])

In [45]:
np.sqrt(y)

array([7.87400787, 8.        , 7.21110255, 3.60555128, 4.        ,
       1.73205081, 6.55743852, 7.93725393, 9.2736185 , 7.87400787,
       7.87400787, 3.60555128])

In [46]:
np.exp(y)

array([8.43835667e+26, 6.23514908e+27, 3.83100800e+22, 4.42413392e+05,
       8.88611052e+06, 2.00855369e+01, 4.72783947e+18, 2.29378316e+27,
       2.23524660e+37, 8.43835667e+26, 8.43835667e+26, 4.42413392e+05])

# Numpy

Numpy is a general-purpose array processing package.It provides a high-performance multidimensional array object, and tools for working with these arrays.It is the fundamental package for scientific computing with Python.

# What is an Array....

An array is a data structure that stores same datatype. In pyhton this is the main difference between arrays and list. While python list can contain values corresponding to different datatypes. Arrays in python can only contain values corresponding to same data type.

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4]
lst

[1, 2, 3, 4]

In [3]:
np.array(lst)

array([1, 2, 3, 4])

In [4]:
arr=np.array(lst)
type(arr)

numpy.ndarray

In [5]:
lst1=[1,2,3,4]
lst2=[2,3,4,5]
lst3=[3,4,5,6]

In [6]:
arr1=np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [7]:
arr1.shape

(3, 4)

In [13]:
#indexing
arr=[1,2,3,4,5]
np.array(arr)

array([1, 2, 3, 4, 5])

In [14]:
arr[4]

5

In [15]:
#change allement
arr[4]=7

In [16]:
arr

[1, 2, 3, 4, 7]

In [17]:
arr[1:4]

[2, 3, 4]

In [18]:
arr[:]

[1, 2, 3, 4, 7]

In [19]:
arr[:5]

[1, 2, 3, 4, 7]

In [20]:
arr[0:]

[1, 2, 3, 4, 7]

In [21]:
arr[:-1]

[1, 2, 3, 4]

In [22]:
arr[:-2]

[1, 2, 3]

In [23]:
arr[::]

[1, 2, 3, 4, 7]

In [24]:
arr[::-1]

[7, 4, 3, 2, 1]

In [26]:
arr[::-2]

[7, 3, 1]

In [27]:
arr[::-3]

[7, 2]

In [28]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [30]:
arr1[:,:1]

array([[1],
       [2],
       [3]])

In [31]:
arr1[:,1]

array([2, 3, 4])

In [32]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [34]:
arr1[:2,1:3]

array([[2, 3],
       [3, 4]])

In [35]:
#EDA
arr

[1, 2, 3, 4, 7]

In [38]:
arry=np.array(arr)
arry

array([1, 2, 3, 4, 7])

In [39]:
arry<2

array([ True, False, False, False, False])

In [40]:
arry[arry<2]

array([1])

In [41]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [43]:
arr2=arr1.reshape(4,3)
arr2

array([[1, 2, 3],
       [4, 2, 3],
       [4, 5, 3],
       [4, 5, 6]])

In [45]:
arr3=arr1.reshape(2,6)
arr3

array([[1, 2, 3, 4, 2, 3],
       [4, 5, 3, 4, 5, 6]])

In [46]:
arr4=arr1.reshape(1,12)
arr4

array([[1, 2, 3, 4, 2, 3, 4, 5, 3, 4, 5, 6]])

In [47]:
#machenism to create array....
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,10,1).reshape(3,3)#2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.arange(1,10,1).reshape(9,1,1)#3d

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])